stop cleaning homebrew due to 'Permission denied' complaints afterwards
https://travis-ci.com/tobiipro/lodash-firecloud/jobs/276244772#L392

error: cannot lock ref 'refs/remotes/origin/master': Unable to create '/home/linuxbrew/.linuxbrew/Homebrew/.git/refs/remotes/origin/master.lock': Permission denied